# Generated by Django 3.2.4 on 2021-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0002_auto_20210629_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
